[project]
name = "thing2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "trio>=0.27.0",
]

[dependency-groups]
dev = [
    "pip>=24.3.1",
]
